"""add signals table

Revision ID: 02b08bc9370b
Revises: daab9355f437
Create Date: 2026-09-22 14:04:19.327208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02b08bc9370b'
down_revision: Union[str, None] = 'daab9355f437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_video_id', sa.UUID(), nullable=False),
    sa.Column('signal_type', sa.Enum('LOUDNESS_RMS', 'SCENE_CHANGE', 'PAUSE', 'SPEECH_RATE', name='signaltype', native_enum=False, length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('points_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signals')
    # ### end Alembic commands ###
