"""add jobs table

Revision ID: 5d26eebd79c7
Revises: 7d3cd969f7ec
Create Date: 2026-09-22 05:41:53.038243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d26eebd79c7'
down_revision: Union[str, None] = '7d3cd969f7ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_video_id', sa.UUID(), nullable=True),
    sa.Column('stage', sa.Enum('TEST_STAGE', 'UPLOAD_METADATA', 'YOUTUBE_DOWNLOAD', name='jobstage', native_enum=False, length=32), nullable=False),
    sa.Column('state', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='jobstate', native_enum=False, length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_video_id'], ['source_videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
