"""add clip candidate review status and excerpt

Revision ID: a3f6d16eb9cb
Revises: 0f1aaeb5bfa1
Create Date: 2026-09-22 15:21:58.808409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f6d16eb9cb'
down_revision: Union[str, None] = '0f1aaeb5bfa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clip_candidates', sa.Column('transcript_excerpt', sa.Text(), nullable=False))
    op.add_column('clip_candidates', sa.Column('review_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='reviewstatus', native_enum=False, length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clip_candidates', 'review_status')
    op.drop_column('clip_candidates', 'transcript_excerpt')
    # ### end Alembic commands ###
